// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateUserRequest struct {
	Name string `json:"name"`
	Email  string    `json:"email"`
}

type CreateUserResponse struct {
	Name string `json:"name"`
	Email  string    `json:"email"`
	Message string `json:"message"`
}
