// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateUserRequest struct {
	Name string `json:"name"`
	Email  string    `json:"email"`
}

type UserResponse struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}
