// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type UserRequest struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type UserResponse struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}
